### ISSUE TITLE
change this to 2010 vintage census tracts

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/hamilton_property_code_enforcement#2]
https://github.com/geomarker-io/hamilton_property_code_enforcement/blob/f1b2e4585ba7907da284d917affcec21df4c68cd/make_data.R#L31

**Comment by cole-brokamp** [comment]
why didn't this trigger a check?

**Comment by cole-brokamp** [comment]
notify andrew to include in codec

**Comment by erikarasnick** [comment]
@cole-brokamp do we want to change everything here to 2010? Tracts and blocks for estimating number of households?

**Comment by erikarasnick** [comment]
https://github.com/geomarker-io/hamilton_property_code_enforcement/blob/f1b2e4585ba7907da284d917affcec21df4c68cd/make_data.R#L57

This housing variable isn't present in the 2010 block data from tigris.

**Comment by cole-brokamp** [comment]
I think it is okay to use the 2020 housing data to estimate the number of households since we are using block estimates, but to still return the data in 2010 vintage tracts

**Comment by cole-brokamp** [comment]
> This housing variable isn't present in the 2010 block data from tigris. (not just because it is suffixed with `20`, it's not there at all)

I've noticed that is missing as well, but didn't think about it at the time.  `cincy::interpolate` uses the 2020 estimates for population even if we were to interpolate a 2010 tract dataset to 2010 neighborhood dataset, for example.
